"""adding command related tables

Revision ID: 10cd07f3d15d
Revises: bf987b16d0fb
Create Date: 2026-08-17 18:03:10.755837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cd07f3d15d'
down_revision: Union[str, Sequence[str], None] = 'bf987b16d0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computer_id', sa.Integer(), nullable=False),
    sa.Column('command_type', sa.Enum('message', 'lock', 'restart', 'shutdown', name='commandtype', native_enum=False), nullable=False),
    sa.Column('payload', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'delivered', 'executed', 'failed', 'cancelled', name='commandstatus', native_enum=False), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['remote_commands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command_results')
    op.drop_table('remote_commands')
    # ### end Alembic commands ###
