"""adding notification related tables

Revision ID: 3b8ff5f6f4bf
Revises: 10cd07f3d15d
Create Date: 2026-08-22 19:03:49.116544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8ff5f6f4bf'
down_revision: Union[str, Sequence[str], None] = '10cd07f3d15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
